
class ParseApiConfig
  APPLICATION_ID_HEADER = "X-Parse-Application-Id"
  APPLICATION_ID_VALUE = "pb4VAwYShHI5pUbE3ewFojxj5EpU4Nr2o1YZnRIF"
  APPLICATION_REST_API_KEY_HEADER = "X-Parse-REST-API-Key"
  APPLICATION_REST_API_KEY_KEY = "MOTvgHdJ0GyXSkPJ3sYBlKEZxE8HLiMjmpnG07xG"
end