package com.locationhud.autogenpoiapi;

import android.os.AsyncTask;
import android.util.Log;

import com.locationhud.compassdirection.MapPoint;
import com.locationhud.storage.JsonFactory;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

import javax.net.ssl.HttpsURLConnection;

/**
 * Created by Mark on 18/11/2014.
 */
public class GetAutogeneratedPoiListTask extends AsyncTask<Void, Void, Void> {

    private static String API_ENDPOINT = "https://locationhud.herokuapp.com/poi_api/";

    private GetAutogeneratedPoiListTaskCallback callback;
    private double latitude;
    private double longitude;

    private ArrayList<MapPoint> pois = new ArrayList<MapPoint>();

    public GetAutogeneratedPoiListTask(GetAutogeneratedPoiListTaskCallback callback, double latitude, double longitude) {
        this.callback = callback;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    @Override
    protected Void doInBackground(Void... voids) {
        getPoisFromServer();
        return null;
    }

    @Override
    protected void onPostExecute(Void result) {
        callback.onPoiListRetrieved(pois);
    }

    private void getPoisFromServer() {

        HttpsURLConnection conn = null;
        StringBuilder jsonResults = new StringBuilder();
        try {
            StringBuilder sb = new StringBuilder(API_ENDPOINT);
            sb.append("?latitude=" + latitude);
            sb.append("&longitude=" + longitude);

            URL url = new URL(sb.toString());
            conn = (HttpsURLConnection) url.openConnection();
            InputStreamReader in = new InputStreamReader(conn.getInputStream());
            BufferedReader reader = new BufferedReader(in);
            String line;
            while ((line = reader.readLine()) != null) {
                jsonResults.append(line);
            }
        } catch (MalformedURLException e) {
            Log.e("ERROR", "Error processing URL", e);
        } catch (IOException e) {
            Log.e("ERROR", "Error connecting to API", e);
        } finally {
            if (conn != null) {
                conn.disconnect();
            }
        }

        pois = JsonFactory.decodeJsonForPoiList(jsonResults.toString());

    }
}