package com.locationhud.retrieveautogenpoi;

import com.locationhud.compassdirection.MapPoint;

import java.util.ArrayList;

/**
 * Created by Mark on 18/11/2014.
 */
public interface GetAutogeneratedPoiListTaskCallback {
    public void onPoiListRetrieved(ArrayList<MapPoint> pois);
}
